### ISSUE TITLE
nem indul az app

### ISSUE THREAD

**Issue by cuh7b5** [szabbenjamin/ittotttv#15]
Szia!

A telepítés, config beállítás után nem indul el az app. Vajon én rontok el valamit?

```
# npm start

> ittotttv@0.10.0 start
> node tv_servlet.js

Tue Nov 22 2022 11:25:05 GMT+0100 (Central European Standard Time) # #############    Kezdés     ##############
Tue Nov 22 2022 11:25:05 GMT+0100 (Central European Standard Time) # Server is listening: http://127.0.0.1:8081/
Tue Nov 22 2022 11:25:05 GMT+0100 (Central European Standard Time) # Csatornalista generalas...
undefined:1
undefined
^

SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at Request._callback (/home/cuh/ittotttv/engine/ittott.js:134:44)
    at self.callback (/home/cuh/ittotttv/engine/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.onRequestError (/home/cuh/ittotttv/engine/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:488:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)

Node.js v19.1.0
```

**Comment by vobi1024** [comment]
Valóban problémás aktuális nodejs verziókkal, 10.24.1-el működik...
